// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tioxlvekpelevjawtzst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpb3hsdmVrcGVsZXZqYXd0enN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY1MjMsImV4cCI6MjA2NTQ5MjUyM30.NrpNXmfUrm56zOpJ7Z7x1BXqtXGr4z9oo_Nm6MkmV8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);